#
# Pipeline pipeline_seurat.py configuration file
# ==============================================
#

# General options
# ---------------

# Project name
projectname: 10x single cell analysis

# Author
author: Sansom group


# compute resource options
# ------------------------
resources:
  # Number of cores used for parallel jobs
  # (ScaleData and JackStraw)
  numcores: 12


# Gene annotations
# ----------------

annotation:
    # Species
    # Used to obtain gene annotations for gene set analyses
    # Choices: 'hs' (for human) | 'mm' (for mouse)
    species: hs

    # Release of Ensembl gene annotations
    # Choices: 'latest' or a specific number, e.g. 89,90 etc
    ensembl_release: latest


# Pre-run subsetting (optional)
# -----------------------------

subsetcells:
    # Whether subsetting is active
    # Choices: False|True
    active: False
    # Type of subsetting strategy.
    # Choices: 'barcode_list'|'factor'
    # If 'type: barcode_list', specify the location of sample-specific
    # header-less text files containing the identifier of cells to retain (1 per line).
    # To retain all the cells for a sample use the string "use.all"
    # If 'type: factor', the given factor must be a column in metadata.tsv
    type: barcode_list
    factor: condition
    sample_one: /path/to/sample_one_cells_to_keep.txt
    sample_two: use.all
    sample_three: stimulated

blacklist:
    # If active, cells present in the blacklist will be removed
    # per-sample blacklisting is not  supported.
    active: False
    # path specifies location of a header-less text file of cells to remove (1 per line).
    path: /path/to/cells_to_remove.txt

# Run specifications
# ------------------
# - Parameters in "runspecs" accept comma separated lists of arguments
# - All combinations of these parameters will be run.

runspecs:
    # Number(s) of components for initial dimensions reduction
    # (see Seurat::FindClusters)
    #
    # To use automatically identified significant pca components
    # use "sig" (this uses BH adjusted p-values from the JackStraw analysis).
    n_components: 25,sig

    # Clustering resolution(s)
    # (see Seurat::FindClusters)
    cluster_resolutions: 0.6,1

    # Clustering algorithm(s)
    # (see Seurat::FindClusters)
    cluster_algorithms: 1,3

    # Differential expression testing method(s)
    # Choices: 'wilcox'|'bimod'|'roc'|'t'|'tobit'|'poisson'|'negbinom'|'MAST'|'DESeq2'
    de_tests: wilcox

    # Runs to skip (comma separated list of subfolders within each sample directory)
    skip:


# QC parameters
# -------------

qc:
    # A column in metadata.tsv by which cells will be grouped for
    # QC plots, and (if enabled) downsampling
    groupby: sample_id
    ## Creation of the Seurat object (see ?CreateSeuratObject)
    # Include cells where at least this many genes are detected.
    initial_mingenes: 200
    # Include genes with detected expression in at least this many cells.
    mincells: 3
    ## QC Filtering of the Seurat object (see ?FilterCells)
    # Retain cells where at least this many genes are detected
    mingenes: 500
    # Retain cells where at most this proportion of UMI are assigned to mitochondrial genes
    # Note that the default 5% (0.05) can be excessively stringent in some cases
    maxpercentmito: 0.05
    # Whether to downsample to a common number of cells
    # Choices: False|True
    downsamplecells: False


# Regression parameters
# ---------------------

cellcycle:

  # If lists of cell cycle genes are supplied
  # cycle-cycle effects will be visualised by the pipeline.
  # The lists will also be used for regression if specified below.
  #
  # > mouse cell cycle genes >
  #
  # sgenes: /gfs/archive/sansom/datasets/cell_cycle/mouse/s_genes.txt
  # g2mgenes: /gfs/archive/sansom/datasets/cell_cycle/mouse/g2m_genes.txt
  #
  # > human cell cycle genes >
  #
  # sgenes: /gfs/archive/sansom/datasets/cell_cycle/human/wang.g1-s.txt
  # g2mgenes: /gfs/archive/sansom/datasets/cell_cycle/human/wang.g2-m.txt

  sgenes: none
  g2mgenes: none


regress:
    ## Removal of unwanted variation (see Seurat::ScaleData)
    # Latent variables to regress out
    latentvars: nUMI,percent.mito
    # Model used to regress out latent variables
    # Choices: 'linear'|'poisson'|'negbinom'
    modeluse: linear
    # see http://satijalab.org/seurat/cell_cycle_vignette.html
    # Choices: 'none'|'all'|'difference'
    # - Use "all" to regress out all cell cycle effects.
    # - Use "difference" to regress out the difference between G2M and S phase scores
    # (i.e. the Alternate Workflow in the link above)
    cellcycle: none


# Variable gene identification parameters
# ---------------------------------------

vargenes:
    # Either "mean.var.plot" or "dispersion" or "trendvar"
    # use of trendvar is recommended and requires the
    # bioconductor packages "scran" and "scater"
    method: trendvar
    #
    # options for mean.var.plot method
    # --------------------------------
    # Bottom cutoff on y-axis for identifying variable genes (see y.cutoff=...)
    sdcutoff: 1
    # Bottom cutoff on x-axis for identifying variable genes (see x.low.cutoff=...)
    xlowcutoff: 0.1
    # Top cutoff on x-axis for identifying variable genes (see x.high.cutoff=...)
    xhighcutoff: 8
    #
    # options for dispersion method
    # -----------------------------
    # The number of top genes
    topgenes: 1000
    #
    # options for trendvar method
    # ---------------------------
    # Implementation experimental, use at own risk!
    # threshold for identification of genes with significant biological variation
    padjust: 0.05
    # Minimum average expression for inclusion as a variable gene
    # It is has been recommeded to leave this at 0 to allow identification of weak signals
    # from rare cell types. Equivalent to "xlowcutoff" for seurat.
    minmean: 0.01

# Dimension reduction parameters
# ------------------------------

dimreduction:
    ## Determine statistical significance of PCA scores (see seurat_jackstraw.R)
    # Number of replicate samplings to perform (see Seurat::JackStraw)
    jackstraw_n_replicate: 100
    # Type of dimensionality reduction to use for clustering and t-SNE
    # (see Seurat::FindClusters, Seurat::RunTSNE)
    # Choices: 'pca'|'ica'
    method: pca
    # Projection method used for visualisation (umap is recommended)
    # Choices: 'umap'|'tsne'
    visualisation: umap

# Plotting parameters
# -------------------

plot:
    # Groups to be visualised in tSNE/bar plots
    # e.g. 'genotype,cluster'
    # 'cluster' is automatically added if not specified.
    groups: cluster
    # Subgroup used to break down the bar plots and cell counts.
    # Note that it also visualised in t-SNE plots and marker heatmaps
    subgroup:
    # QC variable to be visualised on the tSNE plot
    qcvars: nUMI,percent.mito
    # Column in metadata.tsv represented by the shape of data points
    shape:
    # Opacity of data points
    pointalpha: 0.8
    # Size of data points
    pointsize: 0.5


# tSNE parameters
# ---------------

tsne:
  # Specify up to 9 different values of the perplexity parameters to test
  # Only values strictly less than `floor(ncells/5)` will be considered
  perplexities: 5,10,20,30,50,100
  # A single perplexity value used for downstream plotting and analysis
  perplexity: 30
  maxiter: 10000
  # Choices: True|False
  fast: True


# UMAP parameters
# ----------------

umap:
  # number of neighboring points used for local approximation of the manifold
  # structure
  nneighbors: 30
  # how tightly the embedding is allowed to compress points together
  mindist: 0.3
  # the choice of metric used to measure distance in the input space
  metric: correlation

# Diffusion map parameters
# ------------------------

diffusionmap:
  run: False
  # if usegenes is set to True, the significantly variable genes are used
  # instead of the reduced dimensions - slower but may give better
  # results.
  usegenes: False
  maxdim: 10
  job_memory: "20G"

# RNA Velocity
# ------------

velocity:
  run: False

  ncores: 8
  minmaxclustavemat: 0.2
  minmaxclustavnmat: 0.05
  deltat: 1
  kcells: 15
  fitquantile: 0.02
  neighbourhoodsize: 100
  velocityscale: log
  arrowscale: 3
  arrowlwd: 1.3
  gridflow: TRUE
  mingridcellmass: 0.5
  gridn: 40
  cellalpha: 1
  cellborderalpha: 0.5
  showaxes: TRUE
  plotcex: 1


# Known marker genes
# ------------------

knownmarkers:
  run: False
  # Sets of genes that are specified here will be included in the
  # main report as violin plots.
  #
  # tab-delimited .txt files with columns:
  # gene_id, gene_name, group
  file:

# FindMarkers parameters
# ----------------------

findmarkers:
    ## Differential expression parameters (see Seurat::FindMarkers)
    # Limit testing to genes which show, on average, at least X-fold difference
    # (see logfc.threshold=...)
    threshuse: 0.25
    # Only test genes that are detected in a minimum fraction of min.pct cells
    # (see min.pct=...)
    minpct: 0.1
    #
    # Within-cluster differential expression (optional)
    # ------------------------------------------------
    # Whether to perform within-cluster DE analysis
    # Choices: False|True
    between: False

    # Column in metadata.tsv that contains the factor
    # for within-cluster differential expression analysis, e.g.
    # testfactor: genotype
    between_testfactor: genotype

    # Names of the two levels to compare
    # Note that 'a' is the numerator, 'b' the denominator of fold-changes, e.g.
    # between_a: knockout
    # between_b: wildtype
    between_a: knockout
    between_b: wildtype

    # Conserved cluster marker identification (optional)
    # -------------------------------------------------
    # Identify conserved cluster markers
    conserved: False

    # Set the below to a colname in seurat@metadata
    # to find cluster markers that are conserved
    # across all levels of this factor
    conserved_factor: stim

    conserved_padj: 0.05

    # Conserved differential expression between conditions  (optional)
    # ---------------------------------------------------------------

    # Identify conserved differences between conditions (within-cluster)
    conserved_between: False

    # Set the below to a colname in seurat@metadata
    # to find gene expression differences that are conserved
    # between condition across all levels of this factor
    # (it should be orthogonal to "between_testfactor")
    conserved_between_factor: none

    conserved_between_padj: 0.05


# Gene expression report options
# ------------------------------

exprsreport:

   # Count of up-regulated markers to represent in tSNE plots for each cluster
    n_positive: 50
    # Count of down-regulated markers to represent in tSNE plots for each cluster
    n_negative: 25

    # Make plots from user-defined genelists?
    genelists: False

    # a directory containing manually defined gene lists as
    # tab-delimited .txt files with columns:
    # gene_id, gene_name, common_name (common_name is optional)
    genelist_dir:


# Geneset over-representation analysis
# ------------------------------------
# (GO categories and KEGG pathways are analysed by default)

genesets:
    # A method recognised by the R "p.adjust" function
  # The adjustment is applied to the combined results from
  # all of the clusters.
  padjust_method: BH

  # Should the adjusted p-value be used for producing the
  # summary heatmaps?
  use_adjusted_pvalues: True

  # The p-value threshold to be used for producing the
  # summary heatmaps.
  pvalue_threshold: 0.05

  # The minimum odds ratio to be used for inclusion in the
  # plots
  min_odds_ratio: 1.5

  # The minimum number of over-represented genes for
  # inclusion in the plots
  min_fg_genes: 3

  # Should genesets significantly enriched in all clusters
  # be shown in the summary heatmaps?
  show_common: True

  # Make per-cluster geneset plots where genesets are
  # clustered by over-represented genes
  # either "none" or a comma-separated list of geneset names
  show_detailed: GO.BP

gmt_pathway_files:

  # Arbitrary genesets can be specified here using gmt files.
  # the key is taken as the set name, and the value as the path to the gmt file, i.e.
  # set_name: gmt_file_path
  #
  # note that the below files are species and site specific
  #
  # > human msigdb sets >
  #
  # msigdb_biocarta: /gfs/mirror/msigdb/msigdb_v6.1/msigdb_v6.1_GMTs/c2.cp.biocarta.v6.1.entrez.gmt
  # msigdb_reactome: /gfs/mirror/msigdb/msigdb_v6.1/msigdb_v6.1_GMTs/c2.cp.reactome.v6.1.entrez.gmt
  # msigdb_canonical_pathways: /gfs/mirror/msigdb/msigdb_v6.1/msigdb_v6.1_GMTs/c2.cp.v6.1.entrez.gmt
  # msigdb_tf_motifs: /gfs/mirror/msigdb/msigdb_v6.1/msigdb_v6.1_GMTs/c3.tft.v6.1.entrez.gmt
  # msigdb_immunological_signatures: /gfs/mirror/msigdb/msigdb_v6.1/msigdb_v6.1_GMTs/c7.all.v6.1.entrez.gmt
  #
  # > mouse msigdb sets >
  #
  # msigdb_biocarta: /gfs/mirror/msigdb/msigdb_v6.1/msigdb_v6.1_GMTs/c2.cp.biocarta.v6.1.entrez.mouse.gmt
  # msigdb_reactome: /gfs/mirror/msigdb/msigdb_v6.1/msigdb_v6.1_GMTs/c2.cp.reactome.v6.1.entrez.mouse.gmt
  # msigdb_canonical_pathways: /gfs/mirror/msigdb/msigdb_v6.1/msigdb_v6.1_GMTs/c2.cp.v6.1.entrez.mouse.gmt
  # msigdb_tf_motifs: /gfs/mirror/msigdb/msigdb_v6.1/msigdb_v6.1_GMTs/c3.tft.v6.1.entrez.mouse.gmt
  # msigdb_immunological_signatures: /gfs/mirror/msigdb/msigdb_v6.1/msigdb_v6.1_GMTs/c7.all.v6.1.entrez.mouse.gmt

gmt_celltype_files:
  # > human cell types >
  #
  # xCell: /gfs/mirror/xCell/xCell_entrezID.gmt
  #
