#
# Pipeline pipeline_align.py configuration file
# ==============================================
#

# General options
# ---------------

# Project name
projectname: 10x single cell analysis

# Author
author: Sansom group

# Common alignment options
# -------------------------

align:
  # metavar species a column in the seurat object
  # containing the strata to be aligned
  metavar: condition
  # strata is either "all" or a comma separated list
  strata: all

# CCA Alignment options
# ------------------------
cca:
  memory: 20G
  # Number of cores used for parallel jobs
  # (ScaleData and JackStraw)
  numccs: 30
  niter: 100
  dimsalign: 20

# CCA Alignment options
# ------------------------
zinbwave:
  memory: 10G
  ncpu: 12
  # zinbwave K parameter
  k: 5,10,15,20
  # the formula is passed as the zinbwave X parameter
  # a tilde is not needed here
  formula: "condition"
  # use `-1` to use all cells, otherwise specify size of random sample
  ncells: -1
  # use `-1` to use all genes, otherwise specify size of a random sample
  ngenes: -1
  # parallelisation
  # the "dopar", "multi" and "serial" engines are supported
  # issues have been reported with the multicore backed and also
  # with attempting to use large numbers of cpus...
  engine: multi
